import React from 'react';
import { 
  LayoutTemplate, 
  Box, 
  Link, 
  Image, 
  Type, 
  Video, 
  Music, 
  Shapes, 
  MoreHorizontal, 
  Undo, 
  Redo, 
  Save,
  MousePointer2,
  ChevronLeft,
  ChevronRight,
  Plus,
  Trash2,
  Copy,
  Layers,
  Settings,
  Zap,
  Smartphone,
  MessageSquare,
  Eye,
  ExternalLink,
  ArrowRightCircle,
  PlayCircle,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  AlignVerticalJustifyCenter, // for vertical middle
  AlignHorizontalJustifyCenter, // for horizontal center
  BringToFront,
  SendToBack,
  Lock,
  Unlock,
  Grid3X3,
  Move,
  RotateCw,
  Upload,
  Square,
  Circle,
  Triangle,
  Scissors
} from 'lucide-react';

export const Icons = {
  Template: LayoutTemplate,
  Element: Box,
  Link: Link,
  Image: Image,
  Text: Type,
  Video: Video,
  Audio: Music,
  Shape: Shapes,
  More: MoreHorizontal,
  Undo,
  Redo,
  Save,
  Pointer: MousePointer2,
  ChevronLeft,
  ChevronRight,
  Plus,
  Trash: Trash2,
  Copy,
  Layers,
  Settings,
  Action: Zap,
  Phone: Smartphone,
  Popup: MessageSquare,
  Show: Eye,
  External: ExternalLink,
  GoTo: ArrowRightCircle,
  Play: PlayCircle,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  AlignTop: AlignVerticalJustifyCenter, // reusing for icon
  AlignMiddle: AlignVerticalJustifyCenter,
  AlignBottom: AlignVerticalJustifyCenter,
  BringToFront,
  SendToBack,
  Lock,
  Unlock,
  Grid: Grid3X3,
  Move,
  Rotate: RotateCw,
  Upload,
  Square,
  Circle,
  Triangle,
  RemoveBg: Scissors
};